networks:
  propel-test-net:

services:
  propel-test:
    build:
      context: .
      dockerfile: ./php-container-setup/Dockerfile
    container_name: 'propel-test-php'
    stop_grace_period: 1s
    environment:
      DB_HOSTNAME: db_server
      DB_USER: propel
      DB_PW: propel
      DB_NAME: propel
      ALLOW_TESTS_AS_ROOT: 1
      XDEBUG_CONFIG: "idekey=VSCODE"
      PERPL_HOME: ${PERPL_HOME}
    command: bash
    tty: true
    volumes:
      - ${PERPL_HOME}:${PERPL_HOME}
      - /propel/vendor
      - /tmp/perplQuickBuild/:/tmp/perplQuickBuild/
    working_dir:
      ${PERPL_HOME}
    extra_hosts:
    - "host.ip:${HOST_IP:-host-gateway}"
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - propel-test-net
