alias mysql-perpl="mysql --ssl-verify-server-cert=false -h db_server -u propel -ppropel propel"

alias perpl="'$PERPL_HOME/bin/propel'"
alias perpl-composer="composer --working-dir='$PERPL_HOME'"
alias toperpl="cd '$PERPL_HOME'"

alias fixtures-rm="rm -f '$PERPL_HOME/tests/Fixtures/fixtures_built'"
alias fixtures-mysql="perpl test:prepare --vendor=mysql --dsn='mysql:host=db_server;port=3306;dbname=propel' --user=propel --password=propel --exclude-database"
alias fixtures-postgres="perpl test:prepare --vendor=pgsql --dsn='pgsql:host=db_server;port=5432;dbname=propel' --user=propel --password=propel --exclude-database"
alias fixtures-sqlite="perpl test:prepare --vendor=sqlite --dsn='sqlite:$PERPL_HOME/tests/test.sq3' --exclude-database"

alias rebuild-references="$PERPL_HOME/tests/bin/rebuild-reference-files"

alias init-mysql="'$PERPL_HOME/tests/bin/setup.mysql.sh'"
alias init-postgres="'$PERPL_HOME/tests/bin/setup.pgsql.sh'"
alias init-sqlite="'$PERPL_HOME/tests/bin/setup.sqlite.sh'"

alias perpl-composer="composer --working-dir='$PERPL_HOME'"

alias testagnostic='perpl-composer run-script test:agnostic -- --stop-on-error'
alias testmysql='perpl-composer run-script test:mysql -- --stop-on-error'
alias testpostgres='perpl-composer run-script test:pgsql -- --stop-on-error'
alias testsqlite='perpl-composer run-script test:sqlite -- --stop-on-error'
alias test-full='testagnostic && testmysql'

alias lint="perpl-composer run-script cs-check"
alias lint-clean="perpl-composer run-script cs-fix"
alias lint-edited="perpl-composer run-script cs-check -- \$(git --git-dir='$PERPL_HOME/.git' diff --diff-filter=AM --name-only HEAD src/)"
alias lint-clean-edited="perpl-composer run-script cs-fix -- \$(git --git-dir='$PERPL_HOME/.git' diff --diff-filter=AM --name-only HEAD src/)"
alias lint-objects="perpl-composer cs-check tests/Fixtures/bookstore/build/classes/Propel/Tests/Bookstore/Base/*[^Query].php"
alias lint-queries="perpl-composer cs-check tests/Fixtures/bookstore/build/classes/Propel/Tests/Bookstore/Base/*Query.php"

alias stan="'$PERPL_HOME/vendor/bin/phpstan' analyse --configuration '$PERPL_HOME/phpstan.neon'"
alias stan-edited="stan \$(git --git-dir='$PERPL_HOME/.git' diff --name-only HEAD src/)"
alias stan-objects="stan -a autoload.php.dist $PERPL_HOME/tests/Fixtures/bookstore/build/classes/Propel/Tests/Bookstore/Base/*[^Query].php"
alias stan-queries="stan -a autoload.php.dist $PERPL_HOME/tests/Fixtures/bookstore/build/classes/Propel/Tests/Bookstore/Base/*Query.php"

alias psalm="'$PERPL_HOME/vendor/psalm/phar/psalm.phar'"
alias psalm-baseline="psalm --set-baseline='$PERPL_HOME/psalm-baseline.xml'"

alias fullcheck="stan && psalm"

alias xdebug_cli='export XDEBUG_CONFIG="idekey=VSCODE"' # might already be enabled in docker compose
